# The `server` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

server-mutations_title = Mutations

server-title = Server

server-sessions_blocking = { $blocking_count } session(s) blocking { $blocked } other(s)

server-this_connection = this connection
