# The `shortcuts` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

shortcuts-global-title = [Glöbál]

shortcuts-global-command_palette = [Çömmáñd pálétté]

shortcuts-global-switch_connection = [Swítçh çöññéçtíöñ]

shortcuts-global-switch_to_previous_connection = [Swítçh tö prévíöús çöññéçtíöñ]

shortcuts-global-jump_to_connection_by_position = [Júmp tö çöññéçtíöñ by pösítíöñ]

shortcuts-global-keyboard_shortcuts = [Kéyböárd shörtçúts]

shortcuts-global-settings = [Séttíñgs]

shortcuts-global-new_connection_welcome_screen = [Ñéw çöññéçtíöñ (wélçömé sçrééñ)]

shortcuts-global-quit = [Qúít]

shortcuts-panes-title = [Páñés]

shortcuts-panes-focus_hints = [Shöw á júmp kéy öñ évéry páñél, théñ préss ít]

shortcuts-panes-cycle_focus_forward_back = [Çyçlé föçús förwárd / báçk]

shortcuts-panes-toggle_schema_sidebar = [Tögglé sçhémá sídébár]

shortcuts-panes-split_pane_right = [Splít páñé ríght]

shortcuts-panes-split_pane_down = [Splít páñé döwñ]

shortcuts-panes-focus_next_pane = [Föçús ñéxt páñé]

shortcuts-panes-close_pane = [Çlösé páñé]

shortcuts-panes-maximize_pane = [Máxímízé / réstöré páñé]

shortcuts-panes-equalize_panes = [Éqúálízé páñé sízés]

shortcuts-query_tabs-title = [Qúéry tábs]

shortcuts-query_tabs-new_tab = [Ñéw táb]

shortcuts-query_tabs-close_tab = [Çlösé táb]

shortcuts-query_tabs-next_previous_tab = [Ñéxt / prévíöús táb]

shortcuts-query_tabs-run_query = [Rúñ qúéry]

shortcuts-query_tabs-format_sql = [Förmát SQL]

shortcuts-query_tabs-find_in_query = [Fíñd íñ qúéry…]

shortcuts-query_tabs-explain_query_plan = [Éxpláíñ qúéry (pláñ)]

shortcuts-query_tabs-save_query = [Sávé qúéry]

shortcuts-query_tabs-open_saved_query = [Öpéñ sávéd qúéry…]

shortcuts-query_tabs-leave_the_editor_for_the_result_grid = [Léávé thé édítör för thé résúlt gríd]

shortcuts-result_grid-title = [Résúlt gríd]

shortcuts-result_grid-move_cell_cursor = [Mövé çéll çúrsör]

shortcuts-result_grid-extend_selection = [Éxtéñd séléçtíöñ]

shortcuts-result_grid-row_start_end = [Röw stárt / éñd]

shortcuts-result_grid-first_last_row = [Fírst / lást röw]

shortcuts-result_grid-page_up_down = [Págé úp / döwñ]

shortcuts-result_grid-select_all = [Séléçt áll]

shortcuts-result_grid-go_to_row = [Gö tö röw…]

shortcuts-result_grid-copy_selection = [Çöpy séléçtíöñ]

shortcuts-result_grid-inspect_cell = [Íñspéçt çéll]

shortcuts-result_grid-find_in_loaded_rows = [Fíñd íñ löádéd röws…]

shortcuts-result_grid-filter_rows = [Fíltér röws…]

shortcuts-editing_data-title = [Édítíñg dátá]

shortcuts-editing_data-edit_the_focused_cell = [Édít thé föçúséd çéll]

shortcuts-editing_data-submit_staged_changes = [Súbmít stágéd çháñgés]

shortcuts-editing_data-revert_staged_changes = [Révért stágéd çháñgés]

shortcuts-editing_data-mark_row_s_for_deletion = [Márk röw(s) för délétíöñ]

shortcuts-editing_data-add_a_new_row = [Ádd á ñéw röw]

shortcuts-editing_data-set_cell_to_null = [Sét çéll tö ÑÚLL]

shortcuts-schema_tree-title = [Sçhémá tréé]

shortcuts-schema_tree-move_selection = [Mövé séléçtíöñ]

shortcuts-schema_tree-collapse_expand = [Çöllápsé / éxpáñd]

shortcuts-schema_tree-open_table_preview = [Öpéñ táblé prévíéw]

shortcuts-schema_tree-search_schema_focus_filter = [Séárçh sçhémá (föçús fíltér)]

shortcuts-schema_tree-refresh_schema = [Réfrésh sçhémá]

shortcuts-mongodb_browser-title = [MöñgöDB bröwsér]

shortcuts-mongodb_browser-move_selection_collection_tree_document_grid = [Mövé séléçtíöñ (çölléçtíöñ tréé, döçúméñt gríd)]

shortcuts-mongodb_browser-collapse_expand_a_database = [Çöllápsé / éxpáñd á dátábásé]

shortcuts-mongodb_browser-open_the_highlighted_collection_document = [Öpéñ thé híghlíghtéd çölléçtíöñ / döçúméñt]

shortcuts-mongodb_browser-focus_collection_tree_document_grid = [Föçús çölléçtíöñ tréé / döçúméñt gríd]

shortcuts-mongodb_browser-search_collections_tree_filter_documents_grid = [Séárçh çölléçtíöñs (tréé) / fíltér döçúméñts (gríd)]

shortcuts-dialogs-title = [Díálögs]

shortcuts-dialogs-confirm_connect = [Çöñfírm / çöññéçt]

shortcuts-dialogs-cancel_close = [Çáñçél / çlösé]

shortcuts-dialogs-cycle_controls_trapped = [Çyçlé çöñtröls (tráppéd)]

shortcuts-welcome_screen-title = [Wélçömé sçrééñ]

shortcuts-welcome_screen-move_between_saved_connections = [Mövé bétwééñ sávéd çöññéçtíöñs]

shortcuts-welcome_screen-connect_to_the_highlighted_one = [Çöññéçt tö thé híghlíghtéd öñé]

shortcuts-welcome_screen-edit_the_highlighted_connection = [Édít thé híghlíghtéd çöññéçtíöñ]

shortcuts-welcome_screen-remove_the_highlighted_connection = [Rémövé thé híghlíghtéd çöññéçtíöñ]

shortcuts-welcome_screen-new_connection = [Ñéw çöññéçtíöñ]

shortcuts-title = [Kéyböárd shörtçúts]
