# The `shortcuts` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

shortcuts-global-title = Global

shortcuts-global-command_palette = Command palette

shortcuts-global-switch_connection = Switch connection

shortcuts-global-switch_to_previous_connection = Switch to previous connection

shortcuts-global-jump_to_connection_by_position = Jump to connection by position

shortcuts-global-keyboard_shortcuts = Keyboard shortcuts

shortcuts-global-settings = Settings

shortcuts-global-new_connection_welcome_screen = New connection (welcome screen)

shortcuts-global-quit = Quit

shortcuts-panes-title = Panes

shortcuts-panes-focus_schema_editor_grid = Focus schema / editor / grid

shortcuts-panes-cycle_focus_forward_back = Cycle focus forward / back

shortcuts-panes-toggle_schema_sidebar = Toggle schema sidebar

shortcuts-panes-split_pane_right = Split pane right

shortcuts-panes-split_pane_down = Split pane down

shortcuts-panes-focus_next_pane = Focus next pane

shortcuts-panes-close_pane = Close pane

shortcuts-panes-maximize_pane = Maximize / restore pane

shortcuts-panes-equalize_panes = Equalize pane sizes

shortcuts-query_tabs-title = Query tabs

shortcuts-query_tabs-new_tab = New tab

shortcuts-query_tabs-close_tab = Close tab

shortcuts-query_tabs-next_previous_tab = Next / previous tab

shortcuts-query_tabs-run_query = Run query

shortcuts-query_tabs-format_sql = Format SQL

shortcuts-query_tabs-find_in_query = Find in query…

shortcuts-query_tabs-explain_query_plan = Explain query (plan)

shortcuts-query_tabs-save_query = Save query

shortcuts-query_tabs-open_saved_query = Open saved query…

shortcuts-query_tabs-leave_the_editor_for_the_result_grid = Leave the editor for the result grid

shortcuts-result_grid-title = Result grid

shortcuts-result_grid-move_cell_cursor = Move cell cursor

shortcuts-result_grid-extend_selection = Extend selection

shortcuts-result_grid-row_start_end = Row start / end

shortcuts-result_grid-first_last_row = First / last row

shortcuts-result_grid-page_up_down = Page up / down

shortcuts-result_grid-select_all = Select all

shortcuts-result_grid-go_to_row = Go to row…

shortcuts-result_grid-copy_selection = Copy selection

shortcuts-result_grid-inspect_cell = Inspect cell

shortcuts-result_grid-find_in_loaded_rows = Find in loaded rows…

shortcuts-result_grid-filter_rows = Filter rows…

shortcuts-editing_data-title = Editing data

shortcuts-editing_data-edit_the_focused_cell = Edit the focused cell

shortcuts-editing_data-submit_staged_changes = Submit staged changes

shortcuts-editing_data-revert_staged_changes = Revert staged changes

shortcuts-editing_data-mark_row_s_for_deletion = Mark row(s) for deletion

shortcuts-editing_data-add_a_new_row = Add a new row

shortcuts-editing_data-set_cell_to_null = Set cell to NULL

shortcuts-schema_tree-title = Schema tree

shortcuts-schema_tree-move_selection = Move selection

shortcuts-schema_tree-collapse_expand = Collapse / expand

shortcuts-schema_tree-open_table_preview = Open table preview

shortcuts-schema_tree-search_schema_focus_filter = Search schema (focus filter)

shortcuts-schema_tree-refresh_schema = Refresh schema

shortcuts-mongodb_browser-title = MongoDB browser

shortcuts-mongodb_browser-move_selection_collection_tree_document_grid = Move selection (collection tree, document grid)

shortcuts-mongodb_browser-collapse_expand_a_database = Collapse / expand a database

shortcuts-mongodb_browser-open_the_highlighted_collection_document = Open the highlighted collection / document

shortcuts-mongodb_browser-focus_collection_tree_document_grid = Focus collection tree / document grid

shortcuts-mongodb_browser-search_collections_tree_filter_documents_grid = Search collections (tree) / filter documents (grid)

shortcuts-dialogs-title = Dialogs

shortcuts-dialogs-confirm_connect = Confirm / connect

shortcuts-dialogs-cancel_close = Cancel / close

shortcuts-dialogs-cycle_controls_trapped = Cycle controls (trapped)

shortcuts-welcome_screen-title = Welcome screen

shortcuts-welcome_screen-move_between_saved_connections = Move between saved connections

shortcuts-welcome_screen-connect_to_the_highlighted_one = Connect to the highlighted one

shortcuts-welcome_screen-edit_the_highlighted_connection = Edit the highlighted connection

shortcuts-welcome_screen-remove_the_highlighted_connection = Remove the highlighted connection

shortcuts-welcome_screen-new_connection = New connection

shortcuts-title = Keyboard shortcuts
