# The `copy` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

copy-migrating_pct = [Mígrátíñg… { $pct }%]

copy-copying_pct = [Çöpyíñg… { $pct }%]

copy-migrating_rows = [Mígrátíñg… { $rows } röw(s)]

copy-copying_rows = [Çöpyíñg… { $rows } röw(s)]

copy-migrated_rows = [Mígrátéd { $rows } röw(s)]

copy-copied_rows = [Çöpíéd { $rows } röw(s)]

copy-migration_failed_after = [Mígrátíöñ fáíléd áftér { $rows } röw(s): { $message }]

copy-migration_failed = [Mígrátíöñ fáíléd: { $message }]

copy-copy_failed_after = [Çöpy fáíléd áftér { $rows } röw(s): { $message }]

copy-copy_failed = [Çöpy fáíléd: { $message }]

copy-migration_cancelled_kept = [Mígrátíöñ çáñçélléd ({ $rows } röw(s) képt)]

copy-migration_cancelled = [Mígrátíöñ çáñçélléd]

copy-copy_cancelled_kept = [Çöpy çáñçélléd ({ $rows } röw(s) képt)]

copy-copy_cancelled = [Çöpy çáñçélléd]
