# The `copy` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

copy-migrating_pct = Migrating… { $pct }%

copy-copying_pct = Copying… { $pct }%

copy-migrating_rows = Migrating… { $rows } row(s)

copy-copying_rows = Copying… { $rows } row(s)

copy-migrated_rows = Migrated { $rows } row(s)

copy-copied_rows = Copied { $rows } row(s)

copy-migration_failed_after = Migration failed after { $rows } row(s): { $message }

copy-migration_failed = Migration failed: { $message }

copy-copy_failed_after = Copy failed after { $rows } row(s): { $message }

copy-copy_failed = Copy failed: { $message }

copy-migration_cancelled_kept = Migration cancelled ({ $rows } row(s) kept)

copy-migration_cancelled = Migration cancelled

copy-copy_cancelled_kept = Copy cancelled ({ $rows } row(s) kept)

copy-copy_cancelled = Copy cancelled
