# The `settings` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

settings-tab-appearance = [Áppéáráñçé]

settings-tab-editor = [Édítör]

settings-tab-keymap = [Kéymáp]

settings-tab-behavior = [Béhávíör]

settings-tab-data = [Gríds & résúlts]
    .subtitle = [Défáúlts för évéry gríd: SQL résúlts, Rédís kéys, MöñgöDB döçúméñts.]

settings-tab-sql = [SQL]
    .subtitle = [Ápplíés tö SQL çöññéçtíöñs (PöstgréSQL, MySQL, SQLíté, ÇlíçkHöúsé).]

settings-tab-kv = [Kéy-válúé]
    .subtitle = [Ápplíés tö kéy-válúé çöññéçtíöñs (Rédís). Ñéw tábs stárt fröm thésé.]

settings-tab-doc = [Döçúméñts]
    .subtitle = [Ápplíés tö döçúméñt çöññéçtíöñs (MöñgöDB). Ñéw tábs stárt fröm thésé.]

settings-tab-safety = [Sáféty]
    .subtitle = [Öñé sçálé för évéry éñgíñé: SQL státéméñts, Rédís kéys, MöñgöDB döçúméñts.]

settings-tab-ai = [ÁÍ ágéñt]

settings-tab-about = [Áböút]

settings-group-language = [Láñgúágé]

settings-appearance-locale =
    .label = [Láñgúágé]
    .help = [Thé íñtérfáçé láñgúágé. "Systém" föllöws thé öpérátíñg systém, fállíñg báçk tö Éñglísh whéñ thát láñgúágé hás ñö tráñslátíöñ.]

settings-appearance-locale-seg-system = [Systém]

settings-appearance-locale-seg-english = [Éñglísh]

settings-appearance-locale-seg-pseudo = [Pséúdö]

settings-group-motion = [Mötíöñ]

settings-appearance-reduce_motion =
    .label = [Rédúçé mötíöñ]
    .help = [Súppréss ñöñ-ésséñtíál áñímátíöñ, för mötíöñ séñsítívíty.]

settings-group-layout = [Láyöút]

settings-editor-line_height =
    .label = [Líñé héíght]
    .help = [Édítör líñé spáçíñg, ás á múltíplé öf thé föñt sízé.]

settings-editor-line_height-seg-tight = [Tíght]

settings-editor-line_height-seg-normal = [Ñörmál]

settings-editor-line_height-seg-loose = [Löösé]

settings-editor-tab_width =
    .label = [Táb wídth]
    .help = [Spáçés á táb öççúpíés íñ thé SQL édítör.]

settings-editor-tab_width-seg-2 = [2]

settings-editor-tab_width-seg-4 = [4]

settings-editor-tab_width-seg-8 = [8]

settings-group-navigation = [Ñávígátíöñ]

settings-keymap-vim_mode =
    .label = [Vím ñávígátíöñ]
    .help = [Ádds hjkl / g / G / Çtrl-d / Çtrl-ú mötíöñs tö thé résúlt gríd áñd thé hístöry döçk, álöñgsídé thé árröw kéys. Ápplíés lívé.]

settings-group-startup = [Stártúp]

settings-behavior-restore_last_session =
    .label = [Réstöré lást séssíöñ]
    .help = [Réçöññéçt tö thé möst réçéñtly úséd çöññéçtíöñ öñ láúñçh (çrédéñtíáls çömé fröm thé kéyçháíñ). Tákés éfféçt ñéxt láúñçh.]

settings-group-display = [Díspláy]

settings-data-density =
    .label = [Röw déñsíty]
    .help = [Vértíçál spáçíñg öf röws, íñ évéry gríd.]

settings-data-density-seg-compact = [Çömpáçt]

settings-data-density-seg-comfortable = [Çömförtáblé]

settings-data-density-seg-spacious = [Spáçíöús]

settings-data-null_display =
    .label = [Ñúll díspláy]
    .help = [Höw á SQL ÑÚLL réñdérs íñ á çéll. Sét áñy öthér stríñg íñ thé fílé.]

settings-data-null_display-seg-null = [ÑÚLL]

settings-data-null_display-seg- = [∅]

settings-data-null_display-seg-blank = [bláñk]

settings-data-row_numbers =
    .label = [Röw ñúmbérs]
    .help = [Shöw thé léádíñg röw-ñúmbér gúttér íñ SQL résúlts.]

settings-group-performance = [Pérförmáñçé]

settings-data-page_size =
    .label = [Págé sízé]
    .help = [Röws fétçhéd pér págé ás yöú sçröll, íñ évéry gríd. Lárgér méáñs féwér röúñd-tríps áñd möré résídéñt röws.]

settings-data-page_size-seg-100 = [100]

settings-data-page_size-seg-200 = [200]

settings-data-page_size-seg-500 = [500]

settings-data-page_size-seg-1000 = [1000]

settings-data-max_cell_chars =
    .label = [Máx çéll sízé]
    .help = [Bytés öf á síñglé çéll képt résídéñt, thé fát-çéll mémöry ráíl. Övér-çáp çélls áré çlíppéd för díspláy öñly; éxpört stáys fúll.]

settings-data-max_cell_chars-seg-1k = [1K]

settings-data-max_cell_chars-seg-4k = [4K]

settings-data-max_cell_chars-seg-16k = [16K]

settings-data-max_cell_chars-seg-64k = [64K]

settings-data-stats_distinct_max_rows =
    .label = [Státs dístíñçt límít]
    .help = [Résúlt sízé pást whíçh thé çölúmñ-státs bár wíthhölds çöúñt(dístíñçt) úñtíl yöú çlíçk çömpúté, sö ít ñévér sçáñs á húgé táblé by áççídéñt.]

settings-data-stats_distinct_max_rows-seg-100k = [100K]

settings-data-stats_distinct_max_rows-seg-1m = [1M]

settings-data-stats_distinct_max_rows-seg-10m = [10M]

settings-data-stats_distinct_max_rows-seg-always = [Álwáys]

settings-data-copy_row_limit =
    .label = [Çöpy röw límít]
    .help = [Röws á séléçt-áll ör whölé-çölúmñ çöpy púlls íñtö thé çlípböárd. Lárgér çöpíés áré çlíppéd tö thís (wíth á wárñíñg) tö böúñd mémöry.]

settings-data-copy_row_limit-seg-10k = [10K]

settings-data-copy_row_limit-seg-100k = [100K]

settings-data-copy_row_limit-seg-500k = [500K]

settings-data-copy_row_limit-seg-1m = [1M]

settings-group-large_result_safety = [Lárgé-résúlt sáféty]

settings-sql-auto_limit =
    .label = [Áútö-límít]
    .help = [Áppéñd LÍMÍT tö á báré SÉLÉÇT * sö á fát táblé çáñ't flööd thé gríd.]

settings-sql-auto_limit-seg-off = [Öff]

settings-sql-auto_limit-seg-100 = [100]

settings-sql-auto_limit-seg-1000 = [1000]

settings-sql-auto_limit-seg-10000 = [10000]

settings-sql-statement_timeout =
    .label = [Státéméñt tíméöút]
    .help = [Ábört á qúéry (áñd íts págé/rúñ fétçhés) thát rúñs löñgér tháñ thís.]

settings-sql-statement_timeout-seg-off = [Öff]

settings-sql-statement_timeout-seg-10s = [10s]

settings-sql-statement_timeout-seg-30s = [30s]

settings-sql-statement_timeout-seg-60s = [60s]

settings-group-watch = [Wátçh]

settings-sql-watch_default_secs =
    .label = [Défáúlt wátçh íñtérvál]
    .help = [Árm wátçh át thís íñtérvál öñ évéry résúlt thát çáñ táké öñé. Öff méáñs wátçh stárts öñly whéñ yöú ásk för ít.]

settings-sql-watch_default_secs-seg-off = [Öff]

settings-sql-watch_default_secs-seg-5s = [5s]

settings-sql-watch_default_secs-seg-10s = [10s]

settings-sql-watch_default_secs-seg-30s = [30s]

settings-sql-watch_min_secs =
    .label = [Míñímúm wátçh íñtérvál]
    .help = [Flöör úñdér áñy wátçh íñtérvál. Á wátçh ís á qúéry öñ á lööp, sö thís ís á löád gúárd; prödúçtíöñ çöññéçtíöñs áré flööréd át 10s régárdléss.]

settings-sql-watch_min_secs-seg-1s = [1s]

settings-sql-watch_min_secs-seg-2s = [2s]

settings-sql-watch_min_secs-seg-5s = [5s]

settings-group-browsing = [Bröwsíñg]

settings-kv-default_query_mode =
    .label = [Défáúlt fíltér mödé]
    .help = [Höw á ñéw bröwsé táb's fíltér böx réáds whát yöú typé. Çháñgéáblé pér táb fröm thé fíltér dröpdöwñ.]

settings-kv-default_query_mode-seg-glob = [Glöb]

settings-kv-default_query_mode-seg-prefix = [Préfíx]

settings-kv-default_query_mode-seg-exact = [Éxáçt]

settings-kv-default_query_mode-seg-fuzzy = [Fúzzy]

settings-kv-default_query_mode-seg-value = [Válúé]

settings-kv-auto_refresh_secs =
    .label = [Áútö-réfrésh kéys]
    .help = [Höw öftéñ á ñéw kéy-bröwsér táb ré-sçáñs thé kéyspáçé. Öff by défáúlt; çháñgé ít för áñ öpéñ táb fröm thé bröwsér's áçtíöñs méñú.]

settings-kv-auto_refresh_secs-seg-off = [Öff]

settings-kv-auto_refresh_secs-seg-2s = [2s]

settings-kv-auto_refresh_secs-seg-5s = [5s]

settings-kv-auto_refresh_secs-seg-10s = [10s]

settings-kv-auto_refresh_secs-seg-30s = [30s]

settings-kv-max_resident_keys =
    .label = [Máx résídéñt kéys]
    .help = [Kéys öñé bröwsé táb kééps íñ mémöry béföré évíçtíñg thé öldést, sö á löñg úñfíltéréd bröwsé çáñ't gröw wíthöút böúñd.]

settings-kv-max_resident_keys-seg-5k = [5K]

settings-kv-max_resident_keys-seg-20k = [20K]

settings-kv-max_resident_keys-seg-100k = [100K]

settings-kv-max_resident_keys-seg-500k = [500K]

settings-kv-preview_count =
    .label = [Çölléçtíöñ prévíéw sízé]
    .help = [Éléméñts öf á líst ör stréám thé íñspéçtör púlls pér fétçh.]

settings-kv-preview_count-seg-50 = [50]

settings-kv-preview_count-seg-200 = [200]

settings-kv-preview_count-seg-1000 = [1000]

settings-kv-preview_count-seg-5000 = [5000]

settings-doc-default_view =
    .label = [Défáúlt víéw]
    .help = [Höw á ñéwly-öpéñéd çölléçtíöñ réñdérs. Çháñgéáblé pér táb fröm thé çölléçtíöñ töölbár.]

settings-doc-default_view-seg-table = [Táblé]

settings-doc-default_view-seg-list = [Líst]

settings-doc-default_view-seg-json = [JSÖÑ]

settings-doc-max_columns =
    .label = [Máx táblé çölúmñs]
    .help = [Töp-lévél fíélds thé sámpléd-çölúmñ táblé shöws. Á wídér döçúméñt ís stíll whölé íñ Líst, JSÖÑ, áñd thé íñspéçtör.]

settings-doc-max_columns-seg-8 = [8]

settings-doc-max_columns-seg-12 = [12]

settings-doc-max_columns-seg-24 = [24]

settings-doc-max_columns-seg-64 = [64]

settings-group-confirmations = [Çöñfírmátíöñs]

settings-safety-confirm_from =
    .label = [Çöñfírm fröm]
    .help = [Höw dáñgéröús áñ áçtíöñ hás tö bé béföré RÉD ásks fírst. "Rísky" çövérs áñ ÚPDÁTÉ ör DÉLÉTÉ wíth ñö WHÉRÉ, á prívílégé çháñgé, á Rédís kéy délété, ör á MöñgöDB döçúméñt délété; "Déstrúçtívé" ís á DRÖP ör TRÚÑÇÁTÉ, álwáys çöñfírméd by typíñg thé öbjéçt's ñámé. Á çöññéçtíöñ márkéd Pröd çöñfírms fröm Rísky whátévér thís sáys.]

settings-safety-confirm_from-seg-any_write = [Áñy wríté]

settings-safety-confirm_from-seg-risky = [Rísky]

settings-safety-confirm_from-seg-destructive = [Déstrúçtívé]

settings-safety-confirm_from-seg-never = [Ñévér]

settings-safety-confirm_close_tab =
    .label = [Çöñfírm çlösíñg á táb]
    .help = [Ásk béföré çlösíñg á táb thát hölds úñsávéd wörk.]

settings-group-review = [Révíéw]

settings-safety-ai_review =
    .label = [Ásk thé ássístáñt tö révíéw]
    .help = [Ádd á séçöñd öpíñíöñ fröm yöúr ÁÍ ágéñt tö thé çöñfírmátíöñ, för thé místákés á kéywörd çhéçk çáñ't séé (á fíltér thát lööks íñvértéd, sáy). Thís séñds thé státéméñt áñd á súmmáry öf yöúr sçhémá tö thé çöñfígúréd prövídér. Ít ís ádvíçé öñly: ít ñévér rúñs áñythíñg, áñd ñévér úñlöçks thé çöñfírmátíöñ.]

settings-ai-enabled =
    .label = [Éñáblé ágéñt]
    .help = [Thé gröúñdéd çhát sídépáñél (⌘L). Öff ís á trúé kíll swítçh.]

settings-group-database_access = [Dátábásé áççéss]

settings-ai-tier =
    .label = [Áççéss tíér]
    .help = [Höw múçh thé ágéñt çáñ séé. Öff: ñöthíñg. Sçhémá: strúçtúré öñly. Réád: çáppéd SÉLÉÇT/ÉXPLÁÍÑ. Wríté: ádds ÍÑSÉRT/ÚPDÁTÉ/DÉLÉTÉ, éáçh ñéédíñg pér-státéméñt ápprövál.]

settings-ai-tier-seg-off = [Öff]

settings-ai-tier-seg-schema = [Sçhémá]

settings-ai-tier-seg-read = [Réád]

settings-ai-tier-seg-write = [Wríté]

settings-group-read_tier_resource_guards = [Réád-tíér résöúrçé gúárds]

settings-ai-limits-max_rows =
    .label = [Máx röws pér qúéry]
    .help = [Çéílíñg öñ röws öñé tööl SÉLÉÇT rétúrñs; á lárgér LÍMÍT ís çlámpéd.]

settings-ai-limits-max_rows-seg-100 = [100]

settings-ai-limits-max_rows-seg-500 = [500]

settings-ai-limits-max_rows-seg-1000 = [1000]

settings-ai-limits-max_rows-seg-5000 = [5000]

settings-ai-limits-max_rows-seg-50000 = [50000]

settings-ai-limits-statement_timeout_ms =
    .label = [Státéméñt tíméöút]
    .help = [Ábört á tööl qúéry thát rúñs löñgér tháñ thís.]

settings-ai-limits-statement_timeout_ms-seg-off = [Öff]

settings-ai-limits-statement_timeout_ms-seg-5s = [5s]

settings-ai-limits-statement_timeout_ms-seg-15s = [15s]

settings-ai-limits-statement_timeout_ms-seg-30s = [30s]

settings-ai-limits-max_result_bytes =
    .label = [Résúlt sízé çáp]
    .help = [Trím á tööl résúlt lárgér tháñ thís béföré háñdíñg ít tö thé mödél.]

settings-ai-limits-max_result_bytes-seg-64_kb = [64 KB]

settings-ai-limits-max_result_bytes-seg-256_kb = [256 KB]

settings-ai-limits-max_result_bytes-seg-1_mb = [1 MB]

settings-ai-limits-max_result_bytes-seg-5_mb = [5 MB]

settings-ai-limits-max_result_bytes-seg-off = [Öff]

settings-ai-limits-max_tool_calls =
    .label = [Tööl çálls pér çhát]
    .help = [Tööl-çáll búdgét för öñé çöñvérsátíöñ; böúñds á rúñáwáy lööp.]

settings-ai-limits-max_tool_calls-seg-25 = [25]

settings-ai-limits-max_tool_calls-seg-50 = [50]

settings-ai-limits-max_tool_calls-seg-100 = [100]

settings-ai-limits-max_tool_calls-seg-200 = [200]

settings-ai-limits-max_tool_calls-seg-500 = [500]

settings-ai-limits-max_tool_calls-seg-off = [Öff]

settings-ai-limits-max_output_tokens =
    .label = [Máx réply léñgth]
    .help = [Çéílíñg öñ thé tökéñs öñé réply máy géñéráté. Á réply thát híts ít ís çöñtíñúéd áútömátíçálly, bút á löñg répört ís çhéápér tö gét íñ öñé páss.]

settings-ai-limits-max_output_tokens-seg-4k = [4K]

settings-ai-limits-max_output_tokens-seg-8k = [8K]

settings-ai-limits-max_output_tokens-seg-16k = [16K]

settings-ai-limits-max_output_tokens-seg-32k = [32K]

settings-ai-limits-max_output_tokens-seg-64k = [64K]

settings-group-safety = [Sáféty]

settings-ai-preview_writes =
    .label = [Prévíéw áfféçtéd röws]
    .help = [Béföré yöú ápprövé áñ ágéñt wríté, çöúñt thé röws ít wöúld çháñgé áñd shöw á féw öf thém. Túrñíñg thís öff léávés thé ápprövál prömpt shöwíñg öñly thé SQL.]

settings-ai-sandbox_timeout_secs =
    .label = [Révíéw tráñsáçtíöñ tíméöút]
    .help = [Höw löñg úñçömmíttéd ágéñt çháñgés wáít för yöúr Çömmít ör Röll báçk béföré röllíñg báçk öñ théír öwñ. Áñ öpéñ tráñsáçtíöñ hölds löçks, sö ít çáññöt wáít íñdéfíñítély.]

settings-ai-sandbox_timeout_secs-seg-30s = [30s]

settings-ai-sandbox_timeout_secs-seg-1m = [1m]

settings-ai-sandbox_timeout_secs-seg-2m = [2m]

settings-ai-sandbox_timeout_secs-seg-5m = [5m]

settings-ai-sandbox_timeout_secs-seg-10m = [10m]

settings-ai-show_thinking =
    .label = [Shöw thíñkíñg]
    .help = [Shöw á súmmárízéd “thíñkíñg…” áffördáñçé whílé thé mödél réásöñs.]

settings-group-updates = [Úpdátés]

settings-update-auto_update =
    .label = [Áútömátíç úpdátés]
    .help = [Çhéçk GítHúb för ñéwér sígñéd búílds íñ thé báçkgröúñd áñd stágé thém för á öñé-çlíçk réstárt.]

settings-ui_search = [Séárçh séttíñgs…]

settings-ui_paste_code = [pásté thé çödé fröm yöúr bröwsér]

settings-reset_item_ai_keys = [• ÁÍ prövídér ÁPÍ kéys íñ thé kéyçháíñ]

settings-reset_binary_kept = [Thé RÉD ápplíçátíöñ bíñáry ítsélf ís ñöt rémövéd.]

settings-reset_title = [Rémövé áll RÉD dátá]

settings-ui_dismiss = [Dísmíss]

settings-ui_no_settings_match_your_search = [Ñö séttíñgs mátçh yöúr séárçh.]

settings-ui_search_results = [Séárçh résúlts]

settings-ui_import_theme = [Ímpört thémé…]

settings-ui_open_keymap_file = [Öpéñ kéymáp fílé]

settings-ui_reset_all = [Rését áll]

settings-ui_no_actions_match_your_search = [Ñö áçtíöñs mátçh yöúr séárçh.]

settings-ui_custom = [ÇÚSTÖM]

settings-ui_unset = [Úñsét]

settings-ui_press_a_shortcut_esc_to_cancel = [Préss á shörtçút… · Ésç tö çáñçél]

settings-ui_cancel = [Çáñçél]

settings-ui_remove_all_red_data = [Rémövé áll RÉD dátá…]

settings-ui_choose_folder = [Çhöösé földér…]

settings-ui_reset = [Rését]

settings-ui_default = [DÉFÁÚLT]

settings-ui_sign_out = [Sígñ öút]

settings-ui_save = [Sávé]

settings-ui_remove = [Rémövé]

settings-ui_edit_in_settings_file = [Édít íñ séttíñgs fílé]

settings-ui_starting_sign_in_a_browser_window_will_open_shor = [Stártíñg sígñ-íñ… á bröwsér wíñdöw wíll öpéñ shörtly.]

settings-ui_didn_t_open_open_the_sign_in_page = [Dídñ't öpéñ? Öpéñ thé sígñ-íñ págé]

settings-ui_if_the_browser_shows_a_code_instead_paste_it_her = [Íf thé bröwsér shöws á çödé íñstéád, pásté ít héré:]

settings-ui_submit = [Súbmít]

settings-ui_finishing_sign_in = [Fíñíshíñg sígñ-íñ…]

settings-ui_red_roughly_enough_data_a_fast_native_database_e = [RÉD: Röúghly Éñöúgh Dátá, á fást, ñátívé dátábásé éxplörér.]

settings-ui_open_changelog = [Öpéñ çháñgélög…]

settings-ui_report_a_bug = [Répört á búg…]

settings-ui_download = [Döwñlöád…]

settings-ui_check_for_updates = [Çhéçk för úpdátés]

settings-ui_open_settings_file = [Öpéñ séttíñgs fílé]

settings-ui_done = [Döñé]
