# The `settings` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

settings-tab-appearance = Appearance

settings-tab-editor = Editor

settings-tab-keymap = Keymap

settings-tab-behavior = Behavior

settings-tab-data = Grids & results
    .subtitle = Defaults for every grid: SQL results, Redis keys, MongoDB documents.

settings-tab-sql = SQL
    .subtitle = Applies to SQL connections (PostgreSQL, MySQL, SQLite, ClickHouse).

settings-tab-kv = Key-value
    .subtitle = Applies to key-value connections (Redis). New tabs start from these.

settings-tab-doc = Documents
    .subtitle = Applies to document connections (MongoDB). New tabs start from these.

settings-tab-safety = Safety
    .subtitle = One scale for every engine: SQL statements, Redis keys, MongoDB documents.

settings-tab-ai = AI agent

settings-tab-about = About

settings-group-language = Language

settings-appearance-locale =
    .label = Language
    .help = The interface language. "System" follows the operating system, falling back to English when that language has no translation.

settings-appearance-locale-seg-system = System

settings-appearance-locale-seg-english = English

settings-appearance-locale-seg-pseudo = Pseudo

settings-group-motion = Motion

settings-appearance-reduce_motion =
    .label = Reduce motion
    .help = Suppress non-essential animation, for motion sensitivity.

settings-group-layout = Layout

settings-editor-line_height =
    .label = Line height
    .help = Editor line spacing, as a multiple of the font size.

settings-editor-line_height-seg-tight = Tight

settings-editor-line_height-seg-normal = Normal

settings-editor-line_height-seg-loose = Loose

settings-editor-tab_width =
    .label = Tab width
    .help = Spaces a tab occupies in the SQL editor.

settings-editor-tab_width-seg-2 = 2

settings-editor-tab_width-seg-4 = 4

settings-editor-tab_width-seg-8 = 8

settings-group-navigation = Navigation

settings-keymap-vim_mode =
    .label = Vim navigation
    .help = Adds hjkl / g / G / Ctrl-d / Ctrl-u motions to the result grid and the history dock, alongside the arrow keys. Applies live.

settings-group-startup = Startup

settings-behavior-restore_last_session =
    .label = Restore last session
    .help = Reconnect to the most recently used connection on launch (credentials come from the keychain). Takes effect next launch.

settings-group-display = Display

settings-data-density =
    .label = Row density
    .help = Vertical spacing of rows, in every grid.

settings-data-density-seg-compact = Compact

settings-data-density-seg-comfortable = Comfortable

settings-data-density-seg-spacious = Spacious

settings-data-null_display =
    .label = Null display
    .help = How a SQL NULL renders in a cell. Set any other string in the file.

settings-data-null_display-seg-null = NULL

settings-data-null_display-seg- = ∅

settings-data-null_display-seg-blank = blank

settings-data-row_numbers =
    .label = Row numbers
    .help = Show the leading row-number gutter in SQL results.

settings-group-performance = Performance

settings-data-page_size =
    .label = Page size
    .help = Rows fetched per page as you scroll, in every grid. Larger means fewer round-trips and more resident rows.

settings-data-page_size-seg-100 = 100

settings-data-page_size-seg-200 = 200

settings-data-page_size-seg-500 = 500

settings-data-page_size-seg-1000 = 1000

settings-data-max_cell_chars =
    .label = Max cell size
    .help = Bytes of a single cell kept resident, the fat-cell memory rail. Over-cap cells are clipped for display only; export stays full.

settings-data-max_cell_chars-seg-1k = 1K

settings-data-max_cell_chars-seg-4k = 4K

settings-data-max_cell_chars-seg-16k = 16K

settings-data-max_cell_chars-seg-64k = 64K

settings-data-stats_distinct_max_rows =
    .label = Stats distinct limit
    .help = Result size past which the column-stats bar withholds count(distinct) until you click compute, so it never scans a huge table by accident.

settings-data-stats_distinct_max_rows-seg-100k = 100K

settings-data-stats_distinct_max_rows-seg-1m = 1M

settings-data-stats_distinct_max_rows-seg-10m = 10M

settings-data-stats_distinct_max_rows-seg-always = Always

settings-data-copy_row_limit =
    .label = Copy row limit
    .help = Rows a select-all or whole-column copy pulls into the clipboard. Larger copies are clipped to this (with a warning) to bound memory.

settings-data-copy_row_limit-seg-10k = 10K

settings-data-copy_row_limit-seg-100k = 100K

settings-data-copy_row_limit-seg-500k = 500K

settings-data-copy_row_limit-seg-1m = 1M

settings-group-large_result_safety = Large-result safety

settings-sql-auto_limit =
    .label = Auto-limit
    .help = Append LIMIT to a bare SELECT * so a fat table can't flood the grid.

settings-sql-auto_limit-seg-off = Off

settings-sql-auto_limit-seg-100 = 100

settings-sql-auto_limit-seg-1000 = 1000

settings-sql-auto_limit-seg-10000 = 10000

settings-sql-statement_timeout =
    .label = Statement timeout
    .help = Abort a query (and its page/run fetches) that runs longer than this.

settings-sql-statement_timeout-seg-off = Off

settings-sql-statement_timeout-seg-10s = 10s

settings-sql-statement_timeout-seg-30s = 30s

settings-sql-statement_timeout-seg-60s = 60s

settings-group-watch = Watch

settings-sql-watch_default_secs =
    .label = Default watch interval
    .help = Arm watch at this interval on every result that can take one. Off means watch starts only when you ask for it.

settings-sql-watch_default_secs-seg-off = Off

settings-sql-watch_default_secs-seg-5s = 5s

settings-sql-watch_default_secs-seg-10s = 10s

settings-sql-watch_default_secs-seg-30s = 30s

settings-sql-watch_min_secs =
    .label = Minimum watch interval
    .help = Floor under any watch interval. A watch is a query on a loop, so this is a load guard; production connections are floored at 10s regardless.

settings-sql-watch_min_secs-seg-1s = 1s

settings-sql-watch_min_secs-seg-2s = 2s

settings-sql-watch_min_secs-seg-5s = 5s

settings-group-browsing = Browsing

settings-kv-default_query_mode =
    .label = Default filter mode
    .help = How a new browse tab's filter box reads what you type. Changeable per tab from the filter dropdown.

settings-kv-default_query_mode-seg-glob = Glob

settings-kv-default_query_mode-seg-prefix = Prefix

settings-kv-default_query_mode-seg-exact = Exact

settings-kv-default_query_mode-seg-fuzzy = Fuzzy

settings-kv-default_query_mode-seg-value = Value

settings-kv-auto_refresh_secs =
    .label = Auto-refresh keys
    .help = How often a new key-browser tab re-scans the keyspace. Off by default; change it for an open tab from the browser's actions menu.

settings-kv-auto_refresh_secs-seg-off = Off

settings-kv-auto_refresh_secs-seg-2s = 2s

settings-kv-auto_refresh_secs-seg-5s = 5s

settings-kv-auto_refresh_secs-seg-10s = 10s

settings-kv-auto_refresh_secs-seg-30s = 30s

settings-kv-max_resident_keys =
    .label = Max resident keys
    .help = Keys one browse tab keeps in memory before evicting the oldest, so a long unfiltered browse can't grow without bound.

settings-kv-max_resident_keys-seg-5k = 5K

settings-kv-max_resident_keys-seg-20k = 20K

settings-kv-max_resident_keys-seg-100k = 100K

settings-kv-max_resident_keys-seg-500k = 500K

settings-kv-preview_count =
    .label = Collection preview size
    .help = Elements of a list or stream the inspector pulls per fetch.

settings-kv-preview_count-seg-50 = 50

settings-kv-preview_count-seg-200 = 200

settings-kv-preview_count-seg-1000 = 1000

settings-kv-preview_count-seg-5000 = 5000

settings-doc-default_view =
    .label = Default view
    .help = How a newly-opened collection renders. Changeable per tab from the collection toolbar.

settings-doc-default_view-seg-table = Table

settings-doc-default_view-seg-list = List

settings-doc-default_view-seg-json = JSON

settings-doc-max_columns =
    .label = Max table columns
    .help = Top-level fields the sampled-column table shows. A wider document is still whole in List, JSON, and the inspector.

settings-doc-max_columns-seg-8 = 8

settings-doc-max_columns-seg-12 = 12

settings-doc-max_columns-seg-24 = 24

settings-doc-max_columns-seg-64 = 64

settings-group-confirmations = Confirmations

settings-safety-confirm_from =
    .label = Confirm from
    .help = How dangerous an action has to be before RED asks first. "Risky" covers an UPDATE or DELETE with no WHERE, a privilege change, a Redis key delete, or a MongoDB document delete; "Destructive" is a DROP or TRUNCATE, always confirmed by typing the object's name. A connection marked Prod confirms from Risky whatever this says.

settings-safety-confirm_from-seg-any_write = Any write

settings-safety-confirm_from-seg-risky = Risky

settings-safety-confirm_from-seg-destructive = Destructive

settings-safety-confirm_from-seg-never = Never

settings-safety-confirm_close_tab =
    .label = Confirm closing a tab
    .help = Ask before closing a tab that holds unsaved work.

settings-group-review = Review

settings-safety-ai_review =
    .label = Ask the assistant to review
    .help = Add a second opinion from your AI agent to the confirmation, for the mistakes a keyword check can't see (a filter that looks inverted, say). This sends the statement and a summary of your schema to the configured provider. It is advice only: it never runs anything, and never unlocks the confirmation.

settings-ai-enabled =
    .label = Enable agent
    .help = The grounded chat sidepanel (⌘L). Off is a true kill switch.

settings-group-database_access = Database access

settings-ai-tier =
    .label = Access tier
    .help = How much the agent can see. Off: nothing. Schema: structure only. Read: capped SELECT/EXPLAIN. Write: adds INSERT/UPDATE/DELETE, each needing per-statement approval.

settings-ai-tier-seg-off = Off

settings-ai-tier-seg-schema = Schema

settings-ai-tier-seg-read = Read

settings-ai-tier-seg-write = Write

settings-group-read_tier_resource_guards = Read-tier resource guards

settings-ai-limits-max_rows =
    .label = Max rows per query
    .help = Ceiling on rows one tool SELECT returns; a larger LIMIT is clamped.

settings-ai-limits-max_rows-seg-100 = 100

settings-ai-limits-max_rows-seg-500 = 500

settings-ai-limits-max_rows-seg-1000 = 1000

settings-ai-limits-max_rows-seg-5000 = 5000

settings-ai-limits-max_rows-seg-50000 = 50000

settings-ai-limits-statement_timeout_ms =
    .label = Statement timeout
    .help = Abort a tool query that runs longer than this.

settings-ai-limits-statement_timeout_ms-seg-off = Off

settings-ai-limits-statement_timeout_ms-seg-5s = 5s

settings-ai-limits-statement_timeout_ms-seg-15s = 15s

settings-ai-limits-statement_timeout_ms-seg-30s = 30s

settings-ai-limits-max_result_bytes =
    .label = Result size cap
    .help = Trim a tool result larger than this before handing it to the model.

settings-ai-limits-max_result_bytes-seg-64_kb = 64 KB

settings-ai-limits-max_result_bytes-seg-256_kb = 256 KB

settings-ai-limits-max_result_bytes-seg-1_mb = 1 MB

settings-ai-limits-max_result_bytes-seg-5_mb = 5 MB

settings-ai-limits-max_result_bytes-seg-off = Off

settings-ai-limits-max_tool_calls =
    .label = Tool calls per chat
    .help = Tool-call budget for one conversation; bounds a runaway loop.

settings-ai-limits-max_tool_calls-seg-25 = 25

settings-ai-limits-max_tool_calls-seg-50 = 50

settings-ai-limits-max_tool_calls-seg-100 = 100

settings-ai-limits-max_tool_calls-seg-200 = 200

settings-ai-limits-max_tool_calls-seg-500 = 500

settings-ai-limits-max_tool_calls-seg-off = Off

settings-group-safety = Safety

settings-ai-preview_writes =
    .label = Preview affected rows
    .help = Before you approve an agent write, count the rows it would change and show a few of them. Turning this off leaves the approval prompt showing only the SQL.

settings-ai-sandbox_timeout_secs =
    .label = Review transaction timeout
    .help = How long uncommitted agent changes wait for your Commit or Roll back before rolling back on their own. An open transaction holds locks, so it cannot wait indefinitely.

settings-ai-sandbox_timeout_secs-seg-30s = 30s

settings-ai-sandbox_timeout_secs-seg-1m = 1m

settings-ai-sandbox_timeout_secs-seg-2m = 2m

settings-ai-sandbox_timeout_secs-seg-5m = 5m

settings-ai-sandbox_timeout_secs-seg-10m = 10m

settings-ai-show_thinking =
    .label = Show thinking
    .help = Show a summarized “thinking…” affordance while the model reasons.

settings-group-updates = Updates

settings-update-auto_update =
    .label = Automatic updates
    .help = Check GitHub for newer signed builds in the background and stage them for a one-click restart.

settings-ui_search = Search settings…

settings-ui_paste_code = paste the code from your browser

settings-reset_item_ai_keys = • AI provider API keys in the keychain

settings-reset_binary_kept = The RED application binary itself is not removed.

settings-reset_title = Remove all RED data

settings-ui_dismiss = Dismiss

settings-ui_no_settings_match_your_search = No settings match your search.

settings-ui_search_results = Search results

settings-ui_import_theme = Import theme…

settings-ui_open_keymap_file = Open keymap file

settings-ui_reset_all = Reset all

settings-ui_no_actions_match_your_search = No actions match your search.

settings-ui_custom = CUSTOM

settings-ui_unset = Unset

settings-ui_press_a_shortcut_esc_to_cancel = Press a shortcut… · Esc to cancel

settings-ui_cancel = Cancel

settings-ui_remove_all_red_data = Remove all RED data…

settings-ui_choose_folder = Choose folder…

settings-ui_reset = Reset

settings-ui_default = DEFAULT

settings-ui_sign_out = Sign out

settings-ui_save = Save

settings-ui_remove = Remove

settings-ui_edit_in_settings_file = Edit in settings file

settings-ui_starting_sign_in_a_browser_window_will_open_shor = Starting sign-in… a browser window will open shortly.

settings-ui_didn_t_open_open_the_sign_in_page = Didn't open? Open the sign-in page

settings-ui_if_the_browser_shows_a_code_instead_paste_it_her = If the browser shows a code instead, paste it here:

settings-ui_submit = Submit

settings-ui_finishing_sign_in = Finishing sign-in…

settings-ui_red_roughly_enough_data_a_fast_native_database_e = RED: Roughly Enough Data, a fast, native database explorer.

settings-ui_open_changelog = Open changelog…

settings-ui_report_a_bug = Report a bug…

settings-ui_download = Download…

settings-ui_check_for_updates = Check for updates

settings-ui_open_settings_file = Open settings file

settings-ui_done = Done
