# The `shell` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

shell-disconnect = Disconnect

shell-tab_chooser_hint = Choose what to open in this tab  ·  press 1–6 or ↵

shell-stop_write = Stop

shell-stop_write.help = Ask the server to stop the running statement
