# The `keymap` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

keymap-ToggleCommandPalette =
    .label = [Çömmáñd pálétté]

keymap-SwitchConnection =
    .label = [Swítçh çöññéçtíöñ]

keymap-SwitchToPreviousConnection =
    .label = [Swítçh tö prévíöús çöññéçtíöñ]

keymap-GoToRow =
    .label = [Gö tö röw]

keymap-Quit =
    .label = [Qúít]

keymap-CopyResult =
    .label = [Çöpy séléçtíöñ]

keymap-ToggleInspector =
    .label = [Tögglé çéll íñspéçtör]

keymap-CloseInspector =
    .label = [Çlösé çéll íñspéçtör]

keymap-ToggleAssistant =
    .label = [Tögglé ÁÍ ágéñt]

keymap-ToggleFilter =
    .label = [Tögglé fíltér bár]

keymap-SaveQuery =
    .label = [Sávé qúéry]

keymap-OpenSavedQueries =
    .label = [Öpéñ sávéd qúéry]

keymap-Explain =
    .label = [Éxpláíñ qúéry]

keymap-FormatSql =
    .label = [Förmát SQL]

keymap-NewTab =
    .label = [Ñéw táb]

keymap-CloseTab =
    .label = [Çlösé táb]

keymap-NextTab =
    .label = [Ñéxt táb]

keymap-PrevTab =
    .label = [Prévíöús táb]

keymap-ToggleSidebar =
    .label = [Tögglé sçhémá]

keymap-ToggleHistory =
    .label = [Tögglé hístöry]

keymap-ToggleColumnsPanel =
    .label = [Tögglé çölúmñs páñél]

keymap-RefreshSchema =
    .label = [Réfrésh sçhémá]

keymap-SearchSchema =
    .label = [Séárçh sçhémá]

keymap-FocusSchema =
    .label = [Föçús sçhémá sídébár]

keymap-FocusEditor =
    .label = [Föçús édítör]

keymap-FocusGrid =
    .label = [Föçús résúlt gríd]

keymap-CycleFocusNext =
    .label = [Çyçlé föçús förwárd]

keymap-CycleFocusPrev =
    .label = [Çyçlé föçús báçk]

keymap-ShowShortcuts =
    .label = [Kéyböárd shörtçúts]

keymap-RunQuery =
    .label = [Rúñ qúéry]

keymap-NewConnection =
    .label = [Ñéw çöññéçtíöñ]

keymap-Settings =
    .label = [Séttíñgs]

keymap-ToggleSplit =
    .label = [Tögglé splít víéw]

keymap-FocusOtherHalf =
    .label = [Föçús öthér splít hálf]

keymap-BeginEdit =
    .label = [Édít çéll]

keymap-SubmitChanges =
    .label = [Súbmít çháñgés]

keymap-RevertChanges =
    .label = [Révért çháñgés]

keymap-DeleteRow =
    .label = [Márk röw för délétíöñ]

keymap-AddRow =
    .label = [Ádd röw]

keymap-SetNull =
    .label = [Sét çéll tö ÑÚLL]

keymap-SelectAll =
    .label = [Séléçt áll]

keymap-FindInResult =
    .label = [Fíñd]
