# The `keymap` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

keymap-ToggleCommandPalette =
    .label = Command palette

keymap-SwitchConnection =
    .label = Switch connection

keymap-SwitchToPreviousConnection =
    .label = Switch to previous connection

keymap-GoToRow =
    .label = Go to row

keymap-GoToObject =
    .label = Go to table

keymap-Quit =
    .label = Quit

keymap-CopyResult =
    .label = Copy selection

keymap-ToggleInspector =
    .label = Toggle cell inspector

keymap-CloseInspector =
    .label = Close cell inspector

keymap-ToggleAssistant =
    .label = Toggle AI agent

keymap-ToggleFilter =
    .label = Toggle filter bar

keymap-SaveQuery =
    .label = Save query

keymap-OpenSavedQueries =
    .label = Open saved query

keymap-Explain =
    .label = Explain query

keymap-FormatSql =
    .label = Format SQL

keymap-NewTab =
    .label = New tab

keymap-CloseTab =
    .label = Close tab

keymap-NextTab =
    .label = Next tab

keymap-PrevTab =
    .label = Previous tab

keymap-ToggleSidebar =
    .label = Toggle schema

keymap-ToggleHistory =
    .label = Toggle history

keymap-ToggleColumnsPanel =
    .label = Toggle columns panel

keymap-RefreshSchema =
    .label = Refresh schema

keymap-SearchSchema =
    .label = Search schema

keymap-CycleFocusNext =
    .label = Cycle focus forward

keymap-CycleFocusPrev =
    .label = Cycle focus back

keymap-ShowShortcuts =
    .label = Keyboard shortcuts

keymap-RunQuery =
    .label = Run query

keymap-NewConnection =
    .label = New connection

keymap-Settings =
    .label = Settings

keymap-ToggleSplit =
    .label = Split pane right

keymap-SplitDown =
    .label = Split pane down

keymap-FocusOtherHalf =
    .label = Focus next pane

keymap-ClosePane =
    .label = Close pane

keymap-MaximizePane =
    .label = Maximize / restore pane

keymap-EqualizePanes =
    .label = Equalize pane sizes

keymap-BeginEdit =
    .label = Edit cell

keymap-SubmitChanges =
    .label = Submit changes

keymap-RevertChanges =
    .label = Revert changes

keymap-DeleteRow =
    .label = Mark row for deletion

keymap-AddRow =
    .label = Add row

keymap-SetNull =
    .label = Set cell to NULL

keymap-SelectAll =
    .label = Select all

keymap-FindInResult =
    .label = Find
