# The `editor` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

editor-confirm_close_tab = [Çlösé táb]

editor-confirm_close_tabs = [Çlösé tábs]

editor-a11y_query_editor = [Qúéry édítör]

editor-completion_doc_result_column = [résúlt çölúmñ]

editor-completion_doc_bare_column = [çölúmñ]

editor-completion_doc_column = [{ $ty } çölúmñ]

editor-completion_kind_view = [víéw]

editor-completion_doc_view = [Dátábásé víéw.]

editor-completion_kind_table = [táblé]

editor-completion_doc_table = [Dátábásé táblé.]

editor-completion_kind_keyword = [kéywörd]

editor-completion_kind_join = [jöíñ]

editor-new_tab = [Ñéw táb]

editor-no_tab_open = [Ñö qúéry táb öpéñ. Préss ＋ tö stárt]

editor-read_only_badge = [réád-öñly]

editor-run = [Rúñ]

editor-explain = [Éxpláíñ]

editor-save = [Sávé]

editor-read_only_blocked = [Çöññéçtíöñ ís réád-öñly; wríté státéméñts áré dísábléd.]

editor-unpin_tab = [Úñpíñ táb]

editor-pin_tab = [Píñ táb]

editor-tab_close = [Çlösé]

editor-tab_close_others = [Çlösé Öthérs]

editor-tab_close_left = [Çlösé Léft]

editor-tab_close_right = [Çlösé Ríght]

editor-tab_close_all = [Çlösé Áll]

editor-menu_cut = [Çút]

editor-menu_copy = [Çöpy]

editor-menu_paste = [Pásté]

editor-menu_select_all = [Séléçt Áll]

editor-menu_run_selection = [Rúñ séléçtíöñ]

editor-menu_format_selection = [Förmát séléçtíöñ]

editor-menu_run_statement = [Rúñ státéméñt]

editor-menu_format_sql = [Förmát SQL]

editor-menu_explain = [Éxpláíñ]
