# The `editor` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

editor-confirm_close_tab = Close tab

editor-confirm_close_tabs = Close tabs

editor-a11y_query_editor = Query editor

editor-completion_doc_result_column = result column

editor-completion_doc_bare_column = column

editor-completion_doc_column = { $ty } column

editor-completion_kind_view = view

editor-completion_doc_view = Database view.

editor-completion_kind_table = table

editor-completion_doc_table = Database table.

editor-completion_kind_keyword = keyword

editor-completion_kind_join = join

editor-new_tab = New tab

editor-no_tab_open = No query tab open. Press ＋ to start

editor-read_only_badge = read-only

editor-run = Run

editor-explain = Explain

editor-save = Save

editor-read_only_blocked = Connection is read-only; write statements are disabled.

editor-unpin_tab = Unpin tab

editor-pin_tab = Pin tab

editor-tab_close = Close

editor-tab_close_others = Close Others

editor-tab_close_left = Close Left

editor-tab_close_right = Close Right

editor-tab_close_all = Close All

editor-menu_cut = Cut

editor-menu_copy = Copy

editor-menu_paste = Paste

editor-menu_select_all = Select All

editor-menu_run_selection = Run selection

editor-menu_format_selection = Format selection

editor-menu_run_statement = Run statement

editor-menu_format_sql = Format SQL

editor-menu_explain = Explain
