# The `diff` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

diff-comparing = [Çömpáríñg… { $scanned } röw(s) sçáññéd]

diff-row_cap_note = [Thé díff éxçéédéd thé störéd-röw çáp; tötáls áré éxáçt bút sömé dífféríñg röws áréñ't lístéd.]

diff-no_rows = [Ñö dífféríñg röws för thís fíltér.]
