# The `diff` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

diff-comparing = Comparing… { $scanned } row(s) scanned

diff-row_cap_note = The diff exceeded the stored-row cap; totals are exact but some differing rows aren't listed.

diff-no_rows = No differing rows for this filter.
