# The `connect` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

connect-import_intro = [Çhöösé whíçh tööls tö ímpört sávéd çöññéçtíöñs fröm.]

connect-import_title = [Ímpört çöññéçtíöñs]

connect-import_already_added = [Álréády áddéd]

connect-import_select_all = [Séléçt áll]

connect-import_select_title = [Séléçt çöññéçtíöñs]

connect-ph_name = [my dátábásé]

connect-ph_optional = [öptíöñál]

connect-search = [Séárçh çöññéçtíöñs…]

connect-trust_host_body = [Vérífy thé fíñgérpríñt, théñ trúst thís höst tö ádd ít tö ~/.ssh/kñöwñ_hösts.]

connect-confirm_delete = [Délété çöññéçtíöñ]

connect-edit_file = [Édít fílé]

connect-saved_connections = [Sávéd çöññéçtíöñs]

connect-import_from_other_database_tools = [Ímpört fröm öthér dátábásé tööls]

connect-report_a_bug = [Répört á búg]

connect-red = [RÉD]

connect-no_saved_connections_yet = [Ñö sávéd çöññéçtíöñs yét.]

connect-no_connections_match_your_search = [Ñö çöññéçtíöñs mátçh yöúr séárçh.]

connect-btn_previous = [Prévíöús]

connect-btn_next = [Ñéxt]

connect-new_connection = [Ñéw çöññéçtíöñ]

connect-read_only_badge = [réád-öñly]

connect-tip_edit_connection = [Édít çöññéçtíöñ]

connect-tip_duplicate_connection = [Dúplíçáté çöññéçtíöñ]

connect-tip_delete_connection = [Délété çöññéçtíöñ]

connect-field_connection_string = [Çöññéçtíöñ stríñg]

connect-field_name = [Ñámé]

connect-field_engine = [Éñgíñé]

connect-tunnel_via_ssh = [Túññél víá SSH]

connect-field_ssh_host = [SSH höst]

connect-field_ssh_port = [SSH pört]

connect-field_ssh_user = [SSH úsér]

connect-field_authentication = [Áúthéñtíçátíöñ]

connect-field_ssh_password = [SSH pásswörd]

connect-field_private_key_file = [Príváté kéy fílé]

connect-field_key_passphrase_optional = [Kéy pássphrásé (öptíöñál)]

connect-connect_via_proxy = [Çöññéçt víá pröxy]

connect-field_proxy_type = [Pröxy typé]

connect-field_proxy_host = [Pröxy höst]

connect-field_proxy_port = [Pröxy pört]

connect-field_proxy_user_optional = [Pröxy úsér (öptíöñál)]

connect-field_proxy_password_optional = [Pröxy pásswörd (öptíöñál)]

connect-field_database_file = [Dátábásé fílé]

connect-field_host = [Höst]

connect-field_port = [Pört]

connect-field_sentinel_master_optional = [Séñtíñél mástér (öptíöñál)]

connect-field_user = [Úsér]

connect-field_password = [Pásswörd]

connect-field_ai_agent = [ÁÍ ágéñt]

connect-allow_writes = [Állöw wrítés]

connect-field_label = [Lábél]

connect-field_environment = [Éñvíröñméñt]

connect-field_access = [Áççéss]

connect-read_only = [Réád-öñly]

connect-tls = [TLS]

connect-btn_cancel = [Çáñçél]

connect-btn_save = [Sávé]

connect-btn_connect = [Çöññéçt]
