# The `connect` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

connect-import_intro = Choose which tools to import saved connections from.

connect-import_title = Import connections

connect-import_already_added = Already added

connect-import_select_all = Select all

connect-import_select_title = Select connections

connect-ph_name = my database

connect-ph_optional = optional

connect-search = Search connections…

connect-trust_host_body = Verify the fingerprint, then trust this host to add it to ~/.ssh/known_hosts.

connect-confirm_delete = Delete connection

connect-edit_file = Edit file

connect-saved_connections = Saved connections

connect-import_from_other_database_tools = Import from other database tools

connect-report_a_bug = Report a bug

connect-red = RED

connect-no_saved_connections_yet = No saved connections yet.

connect-no_connections_match_your_search = No connections match your search.

connect-btn_previous = Previous

connect-btn_next = Next

connect-new_connection = New connection

connect-read_only_badge = read-only

connect-tip_edit_connection = Edit connection

connect-tip_duplicate_connection = Duplicate connection

connect-tip_delete_connection = Delete connection

connect-field_connection_string = Connection string

connect-field_name = Name

connect-field_engine = Engine

connect-tunnel_via_ssh = Tunnel via SSH

connect-field_ssh_host = SSH host

connect-field_ssh_port = SSH port

connect-field_ssh_user = SSH user

connect-field_authentication = Authentication

connect-field_ssh_password = SSH password

connect-field_private_key_file = Private key file

connect-field_key_passphrase_optional = Key passphrase (optional)

connect-connect_via_proxy = Connect via proxy

connect-field_proxy_type = Proxy type

connect-field_proxy_host = Proxy host

connect-field_proxy_port = Proxy port

connect-field_proxy_user_optional = Proxy user (optional)

connect-field_proxy_password_optional = Proxy password (optional)

connect-field_database_file = Database file

connect-field_host = Host

connect-field_port = Port

connect-field_sentinel_master_optional = Sentinel master (optional)

connect-field_user = User

connect-field_password = Password

connect-field_ai_agent = AI agent

connect-allow_writes = Allow writes

connect-field_label = Label

connect-field_environment = Environment

connect-field_access = Access

connect-read_only = Read-only

connect-tls = TLS

connect-btn_cancel = Cancel

connect-btn_save = Save

connect-btn_connect = Connect
