# The `menu` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

menu-app-about_red = [Áböút RÉD]

menu-app-settings = [Séttíñgs…]

menu-app-services = [Sérvíçés]

menu-app-quit_red = [Qúít RÉD]

menu-connection-title = [Çöññéçtíöñ]

menu-connection-switch_connection = [Swítçh Çöññéçtíöñ…]

menu-connection-new_connection = [Ñéw Çöññéçtíöñ…]

menu-edit-title = [Édít]

menu-edit-cut = [Çút]

menu-edit-copy = [Çöpy]

menu-edit-paste = [Pásté]

menu-edit-select_all = [Séléçt Áll]

menu-edit-copy_result = [Çöpy Résúlt]

menu-view-title = [Víéw]

menu-view-toggle_sidebar = [Tögglé Sídébár]

menu-view-toggle_split_view = [Tögglé Splít Víéw]

menu-view-focus_schema = [Föçús Sçhémá]

menu-view-focus_editor = [Föçús Édítör]

menu-view-focus_grid = [Föçús Gríd]

menu-view-focus_other_split_half = [Föçús Öthér Splít Hálf]

menu-view-cycle_focus_next = [Çyçlé Föçús Ñéxt]

menu-view-cycle_focus_previous = [Çyçlé Föçús Prévíöús]

menu-view-search_schema = [Séárçh Sçhémá]

menu-view-command_palette = [Çömmáñd Pálétté…]

menu-query-title = [Qúéry]

menu-query-run_query = [Rúñ Qúéry]

menu-query-format_sql = [Förmát SQL]

menu-query-er_diagram = [ÉR Díágrám]

menu-query-refresh_schema = [Réfrésh Sçhémá]

menu-query-go_to_row = [Gö tö Röw…]

menu-tabs-title = [Tábs]

menu-tabs-new_tab = [Ñéw Táb]

menu-tabs-next_tab = [Ñéxt Táb]

menu-tabs-previous_tab = [Prévíöús Táb]

menu-tabs-close_tab = [Çlösé Táb]

menu-help-title = [Hélp]

menu-help-whats_new = [Whát's Ñéw]

menu-help-keyboard_shortcuts = [Kéyböárd Shörtçúts]

menu-help-report_a_bug = [Répört á Búg…]
