# The `menu` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

menu-app-about_red = About RED

menu-app-settings = Settings…

menu-app-services = Services

menu-app-quit_red = Quit RED

menu-connection-title = Connection

menu-connection-switch_connection = Switch Connection…

menu-connection-new_connection = New Connection…

menu-edit-title = Edit

menu-edit-cut = Cut

menu-edit-copy = Copy

menu-edit-paste = Paste

menu-edit-select_all = Select All

menu-edit-copy_result = Copy Result

menu-view-title = View

menu-view-toggle_sidebar = Toggle Sidebar

menu-view-toggle_split_view = Toggle Split View

menu-view-focus_schema = Focus Schema

menu-view-focus_editor = Focus Editor

menu-view-focus_grid = Focus Grid

menu-view-focus_other_split_half = Focus Other Split Half

menu-view-cycle_focus_next = Cycle Focus Next

menu-view-cycle_focus_previous = Cycle Focus Previous

menu-view-search_schema = Search Schema

menu-view-command_palette = Command Palette…

menu-query-title = Query

menu-query-run_query = Run Query

menu-query-format_sql = Format SQL

menu-query-er_diagram = ER Diagram

menu-query-refresh_schema = Refresh Schema

menu-query-go_to_row = Go to Row…

menu-tabs-title = Tabs

menu-tabs-new_tab = New Tab

menu-tabs-next_tab = Next Tab

menu-tabs-previous_tab = Previous Tab

menu-tabs-close_tab = Close Tab

menu-help-title = Help

menu-help-whats_new = What's New

menu-help-keyboard_shortcuts = Keyboard Shortcuts

menu-help-report_a_bug = Report a Bug…
