# The `focus` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

focus-history = [Hístöry]

focus-inspector = [Íñspéçtör]

focus-filter_bar = [Fíltér]

focus-find_bar = [Fíñd]

focus-assistant = [ÁÍ ágéñt]

focus-schema = [Sçhémá]

focus-editor = [Édítör]

focus-grid = [Résúlts]

focus-keys = [Kéys]

focus-new_tab = [Ñéw táb]

focus-collections = [Çölléçtíöñs]

focus-documents = [Döçúméñts]
