# The `focus` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

focus-history = History

focus-inspector = Inspector

focus-filter_bar = Filter

focus-find_bar = Find

focus-assistant = AI agent

focus-schema = Schema

focus-editor = Editor

focus-grid = Results

focus-keys = Keys

focus-new_tab = New tab

focus-collections = Collections

focus-documents = Documents
