# The `knowledge` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

knowledge-empty_state = [Thís çöññéçtíöñ hás ñö kñöwlédgé fílé. Thé ágéñt wíll íñfér évérythíñg fröm thé sçhémá.]

knowledge-placeholder = [Whát wöúld yöú téll á ñéw çölléágúé áböút thís dátábásé?]

knowledge-draft_title = [Dráft wríttéñ by thé ágéñt]

knowledge-draft_hint = [Révíéw ít: ít íñférréd thís fröm strúçtúré áñd sámplíñg, áñd ít wíll bé wröñg áböút íñtéñt. Ñöthíñg ís sávéd úñtíl yöú sávé.]

knowledge-hint = [Pláíñ márkdöwñ, földéd íñtö thé ágéñt's prömpt för évéry çhát öñ thís çöññéçtíöñ: whát á métríç méáñs, whíçh jöíñ páth ís thé réál öñé, whíçh táblé ñöt tö çöúñt.]

knowledge-save_hint = [⌘↵ tö sávé]

knowledge-title = [Dátábásé kñöwlédgé - { $name }]

knowledge-cleared = [Çléáréd thé kñöwlédgé fílé för { $name }.]

knowledge-saved = [Sávéd whát thé ágéñt kñöws áböút { $name }.]
