# The `knowledge` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

knowledge-empty_state = This connection has no knowledge file. The agent will infer everything from the schema.

knowledge-placeholder = What would you tell a new colleague about this database?

knowledge-saved = Saved what the agent knows about { $name }.

knowledge-cleared = Cleared the knowledge file for { $name }.

knowledge-draft_title = Draft written by the agent

knowledge-draft_hint = Review it: it inferred this from structure and sampling, and it will be wrong about intent. Nothing is saved until you save.

knowledge-hint = Plain markdown, folded into the agent's prompt for every chat on this connection: what a metric means, which join path is the real one, which table not to count.

knowledge-save_hint = ⌘↵ to save

knowledge-title = Database knowledge - { $name }
