# The `palette` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

palette-cmd_kv_new_tab = [rédís: ñéw táb]

palette-cmd_kv_tree = [rédís: tögglé ñáméspáçé tréé]

palette-cmd_kv_bigkeys = [rédís: fíñd bíggést kéys]

palette-cmd_kv_analyze = [rédís: áñályzé kéyspáçé]

palette-cmd_kv_console = [rédís: öpéñ çöñsölé]

palette-cmd_kv_monitor = [rédís: öpéñ möñítör (slöw lög · çlíéñts)]

palette-cmd_kv_keyspace = [rédís: wátçh kéyspáçé ñötífíçátíöñs]

palette-cmd_kv_pubsub = [rédís: öpéñ púb/súb]

palette-cmd_run = [qúéry: rúñ]

palette-cmd_new_tab = [qúéry: ñéw táb]

palette-cmd_close_tab = [qúéry: çlösé táb]

palette-cmd_next_tab = [qúéry: ñéxt táb]

palette-cmd_prev_tab = [qúéry: prévíöús táb]

palette-cmd_split_right = [víéw: splít páñé ríght]

palette-cmd_split_down = [víéw: splít páñé döwñ]

palette-cmd_focus_other_half = [víéw: föçús ñéxt páñé]

palette-cmd_maximize_pane = [víéw: máxímízé / réstöré páñé]

palette-cmd_equalize_panes = [víéw: éqúálízé páñé sízés]

palette-cmd_unsplit = [víéw: úñsplít (föld páñés báçk íñtö öñé)]

palette-cmd_migrate_schema = [sçhémá: mígráté tö…]

palette-cmd_compare_table = [táblé: çömpáré ágáíñst…]

palette-cmd_goto_row = [gö tö röw…]

palette-cmd_copy = [résúlt: çöpy séléçtíöñ]

palette-cmd_copy_to_table = [résúlt: çöpy tö táblé…]

palette-cmd_add_row = [dátá: ádd röw]

palette-cmd_submit_changes = [dátá: súbmít çháñgés]

palette-cmd_revert_changes = [dátá: révért çháñgés]

palette-cmd_history = [qúéry: tögglé hístöry]

palette-cmd_clear_history = [qúéry: çléár hístöry]

palette-cmd_save_query = [qúéry: sávé…]

palette-cmd_open_saved = [qúéry: öpéñ sávéd…]

palette-cmd_explain = [qúéry: éxpláíñ pláñ]

palette-cmd_explain_analyze = [qúéry: éxpláíñ áñályzé]

palette-cmd_format_sql = [édítör: förmát SQL]

palette-cmd_focus_schema = [föçús: sçhémá sídébár]

palette-cmd_focus_editor = [föçús: édítör]

palette-cmd_focus_grid = [föçús: résúlt gríd]

palette-cmd_search_schema = [sçhémá: séárçh]

palette-cmd_sidebar = [víéw: tögglé sídébár]

palette-cmd_columns = [víéw: tögglé çölúmñs páñél]

palette-cmd_health = [çöññéçtíöñ: héálth répört]

palette-cmd_knowledge = [çöññéçtíöñ: dátábásé kñöwlédgé…]

palette-cmd_compare_schema = [sçhémá: çömpáré ágáíñst…]

palette-cmd_server_panel = [víéw: tögglé sérvér páñél]

palette-cmd_refresh = [sçhémá: réfrésh]

palette-cmd_er_diagram = [sçhémá: ÉR díágrám]

palette-cmd_disconnect = [çöññéçtíöñ: dísçöññéçt]

palette-cmd_ai_new_chat = [ágéñt: ñéw çhát]

palette-cmd_ai_history = [ágéñt: çöñvérsátíöñ hístöry…]

palette-cmd_ai_learn = [ágéñt: léárñ thís dátábásé]

palette-cmd_ai_storage = [ágéñt: öpéñ çöñvérsátíöñ störágé]

palette-cmd_new_conn = [çöññéçtíöñ: ñéw]

palette-cmd_switch_conn = [çöññéçtíöñ: swítçh…]

palette-cmd_shortcuts = [víéw: kéyböárd shörtçúts]

palette-cmd_whats_new = [hélp: whát's ñéw]

palette-cmd_settings = [víéw: séttíñgs]

palette-cmd_settings_file = [séttíñgs: öpéñ fílé]

palette-cmd_settings_default = [séttíñgs: öpéñ défáúlt séttíñgs]

palette-cmd_keymap_file = [kéymáp: çústömízé kéybíñdíñgs]

palette-cmd_remove_all_data = [dáñgér: rémövé áll RÉD dátá…]

palette-search_actions = [Séárçh áçtíöñs ör shörtçúts…]

palette-migrate_target = [{ $schema } ({ $table_count } táblé(s))]
