# The `palette` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

palette-cmd_kv_new_tab = redis: new tab

palette-cmd_kv_tree = redis: toggle namespace tree

palette-cmd_kv_bigkeys = redis: find biggest keys

palette-cmd_kv_analyze = redis: analyze keyspace

palette-cmd_kv_console = redis: open console

palette-cmd_kv_monitor = redis: open monitor (slow log · clients)

palette-cmd_kv_keyspace = redis: watch keyspace notifications

palette-cmd_kv_pubsub = redis: open pub/sub

palette-cmd_run = query: run

palette-cmd_new_tab = query: new tab

palette-cmd_close_tab = query: close tab

palette-cmd_next_tab = query: next tab

palette-cmd_prev_tab = query: previous tab

palette-cmd_split_right = view: split pane right

palette-cmd_split_down = view: split pane down

palette-cmd_focus_other_half = view: focus next pane

palette-cmd_maximize_pane = view: maximize / restore pane

palette-cmd_equalize_panes = view: equalize pane sizes

palette-cmd_unsplit = view: unsplit (fold panes back into one)

palette-cmd_migrate_schema = schema: migrate to…

palette-cmd_compare_table = table: compare against…

palette-cmd_goto_row = go to row…

palette-cmd_copy = result: copy selection

palette-cmd_copy_to_table = result: copy to table…

palette-cmd_add_row = data: add row

palette-cmd_submit_changes = data: submit changes

palette-cmd_revert_changes = data: revert changes

palette-cmd_history = query: toggle history

palette-cmd_clear_history = query: clear history

palette-cmd_save_query = query: save…

palette-cmd_open_saved = query: open saved…

palette-cmd_explain = query: explain plan

palette-cmd_explain_analyze = query: explain analyze

palette-cmd_format_sql = editor: format SQL

palette-cmd_focus_schema = focus: schema sidebar

palette-cmd_focus_editor = focus: editor

palette-cmd_focus_grid = focus: result grid

palette-cmd_search_schema = schema: search

palette-cmd_sidebar = view: toggle sidebar

palette-cmd_columns = view: toggle columns panel

palette-cmd_health = connection: health report

palette-cmd_knowledge = connection: database knowledge…

palette-cmd_compare_schema = schema: compare against…

palette-cmd_refresh = schema: refresh

palette-cmd_er_diagram = schema: ER diagram

palette-cmd_disconnect = connection: disconnect

palette-cmd_ai_new_chat = agent: new chat

palette-cmd_ai_history = agent: conversation history…

palette-cmd_ai_learn = agent: learn this database

palette-cmd_ai_storage = agent: open conversation storage

palette-cmd_new_conn = connection: new

palette-cmd_server_panel = view: toggle server panel

palette-cmd_switch_conn = connection: switch…

palette-cmd_shortcuts = view: keyboard shortcuts

palette-cmd_whats_new = help: what's new

palette-cmd_settings = view: settings

palette-cmd_settings_file = settings: open file

palette-cmd_settings_default = settings: open default settings

palette-cmd_keymap_file = keymap: customize keybindings

palette-cmd_remove_all_data = danger: remove all RED data…

palette-search_actions = Search actions or shortcuts…

palette-migrate_target = { $schema } ({ $table_count } table(s))
