# The `doc` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

doc-aggregation_stage = [Ággrégátíöñ stágé]

doc-field = [fíéld]

doc-value = [válúé]

doc-new_index = [Ñéw íñdéx]

doc-aggregation_pipeline_e_g_group_runs = [Ággrégátíöñ pípélíñé, é.g. [ {"{"} "$group": … {"}"} ]. ⌘↵ rúñs.]

doc-mongodb_aggregation_pipeline = [MöñgöDB ággrégátíöñ pípélíñé]

doc-mongodb_document_editor = [MöñgöDB döçúméñt édítör]

doc-search_collections = [Séárçh çölléçtíöñs…]

doc-read_only = [réád-öñly]

doc-confirm = [Çöñfírm]

doc-actions = [Áçtíöñs]

doc-fields = [Fíélds]

doc-clear_sort = [çléár sört]

doc-aggregation_pipeline_extended_json_array_of_stag = [Ággrégátíöñ pípélíñé (éxtéñdéd JSÖÑ árráy öf stágés)]

doc-select_a_collection_from_the_sidebar_to_open_it_ = [Séléçt á çölléçtíöñ fröm thé sídébár tö öpéñ ít héré.]

doc-copy_collection = [Çöpy çölléçtíöñ]

doc-import_documents = [Ímpört döçúméñts]

doc-export_documents = [Éxpört döçúméñts]

doc-validation_rule = [MöñgöDB válídátíöñ rúlé]

doc-validation_rules = [Válídátíöñ rúlés]
