# The `doc` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

doc-aggregation_stage = Aggregation stage

doc-field = field

doc-value = value

doc-new_index = New index

doc-aggregation_pipeline_e_g_group_runs = Aggregation pipeline, e.g. [ {"{"} "$group": … {"}"} ]. ⌘↵ runs.

doc-mongodb_aggregation_pipeline = MongoDB aggregation pipeline

doc-mongodb_document_editor = MongoDB document editor

doc-search_collections = Search collections…

doc-read_only = read-only

doc-confirm = Confirm

doc-actions = Actions

doc-fields = Fields

doc-clear_sort = clear sort

doc-aggregation_pipeline_extended_json_array_of_stag = Aggregation pipeline (extended JSON array of stages)

doc-select_a_collection_from_the_sidebar_to_open_it_ = Select a collection from the sidebar to open it here.

doc-copy_collection = Copy collection

doc-import_documents = Import documents

doc-export_documents = Export documents

doc-validation_rule = MongoDB validation rule

doc-validation_rules = Validation rules
