# The `kv` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

kv-confirm_delete_key_body = [Thís kéy áñd íts válúé wíll bé pérmáñéñtly délétéd fröm Rédís. Thís çáñ't bé úñdöñé.]

kv-confirm_delete_key = [Délété kéy]

kv-seconds_blank_no_expiry = [séçöñds, bláñk = ñö éxpíry]

kv-claim_to_consumer = [çláím tö çöñsúmér…]

kv-key_name = [kéy ñámé…]

kv-field = [fíéld…]

kv-value = [válúé…]

kv-score_e_g_1_0 = [sçöré (é.g. 1.0)]

kv-seconds_optional = [séçöñds (öptíöñál)]

kv-imported_commands = [Ímpörtéd { $ok } çömmáñd(s)]

kv-imported_with_failures = [Ímpörtéd { $ok }, { $failed } fáíléd{ $detail }]

kv-import_stopped = [Ímpört stöppéd áftér { $ok } çömmáñd(s); { $failed } fáíléd]

kv-actions = [Áçtíöñs]

kv-toggle_namespace_tree = [Tögglé ñáméspáçé tréé]

kv-toggle_favourites_only_filter = [Tögglé fávöúrítés-öñly fíltér]

kv-new_key = [Ñéw kéy]

kv-importing = [Ímpörtíñg…]

kv-commands_ready = [{ $count } çömmáñd(s) réády tö rúñ]

kv-import_destructive = [{ $count } déstrúçtívé çömmáñd(s) íñ thís fílé:]

kv-import_keys = [Ímpört kéys]

kv-this_cant_be_undone = [Thís çáñ't bé úñdöñé.]

kv-delete_key = [Délété kéy]

kv-rename_key = [Réñámé kéy]

kv-toggle_favourite = [Tögglé fávöúríté]

kv-close = [Çlösé]

kv-close_inspector = [Çlösé íñspéçtör]

kv-preview_truncated = [Prévíéw trúñçátéd]

kv-edit = [Édít]

kv-edit_item = [Édít ítém]

kv-delete = [Délété]

kv-delete_item = [Délété ítém]

kv-no_consumers = [Ñö çöñsúmérs.]

kv-nothing_pending_all_delivered_entries_are_acknowledged = [Ñöthíñg péñdíñg — áll délívéréd éñtríés áré áçkñöwlédgéd.]

kv-edit_element = [Édít éléméñt]

kv-delete_element = [Délété éléméñt]

kv-copied_one_key = [Çöpíéd 1 kéy]

kv-copied_keys_ok = [Çöpíéd { $copied } kéys]

kv-copied_keys = [Çöpíéd { $copied } kéy(s), { $failed } fáíléd]

kv-note = [ñöté…]

kv-tags_comma_separated = [tágs, çömmá-sépárátéd…]

kv-type_a_command_e_g_get_mykey_then_enter = [Typé á çömmáñd, é.g. GÉT mykéy, théñ Éñtér…]

kv-console_hint = [Öñé çömmáñd pér líñé. # çömméñts áñd bláñks áré skíppéd. ⌘↵ rúñs áll.]

kv-redis_batch_composer = [Rédís bátçh çömpösér]

kv-batch_stopped = [Bátçh stöppéd — { $ok } ök, { $failed } fáíléd]

kv-batch_ran = [Bátçh ráñ { $ok } çömmáñd(s)]

kv-batch_partial = [Bátçh: { $ok } ök, { $failed } fáíléd]

kv-batch_destructive_confirm = [Thís bátçh çöñtáíñs { $destructive } déstrúçtívé çömmáñd(s). Rúñ áll { $total } líñé(s)?]

kv-tab_to_complete = [Táb tö çömplété]

kv-keyspace_watching = [wátçhíñg { $pattern } — { $events } évéñt(s), { $cfg }]

kv-keyspace_idle = [ñöt wátçhíñg — { $cfg }]

kv-slowlog_loading = [Löádíñg slöw lög…]

kv-slowlog_count = [{ $n } slöw çömmáñd(s)]

kv-no_slow_commands_logged = [Ñö slöw çömmáñds löggéd.]

kv-monitor_paused = [páúséd — { $n } líñé(s) héld]

kv-monitor_streaming = [stréámíñg évéry çömmáñd — { $n } líñé(s)]

kv-monitor_stopped = [stöppéd (MÖÑÍTÖR stréáms évéry çömmáñd thé sérvér rúñs)]

kv-clients_loading = [Löádíñg çlíéñts…]

kv-clients_count = [{ $n } çöññéçtéd çlíéñt(s)]

kv-no_connected_clients = [Ñö çöññéçtéd çlíéñts.]

kv-channel_pattern_e_g_news = [Çháññél páttérñ, é.g. ñéws.*]

kv-pubsub_listening = [lístéñíñg öñ "{ $pattern }", { $messages } mésságé(s)]

kv-pubsub_idle = [ñöt súbsçríbéd]
