# The `kv` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

kv-confirm_delete_key_body = This key and its value will be permanently deleted from Redis. This can't be undone.

kv-confirm_delete_key = Delete key

kv-seconds_blank_no_expiry = seconds, blank = no expiry

kv-claim_to_consumer = claim to consumer…

kv-key_name = key name…

kv-field = field…

kv-value = value…

kv-score_e_g_1_0 = score (e.g. 1.0)

kv-seconds_optional = seconds (optional)

kv-import_stopped = Import stopped after { $ok } command(s); { $failed } failed

kv-imported_commands = Imported { $ok } command(s)

kv-imported_with_failures = Imported { $ok }, { $failed } failed{ $detail }

kv-actions = Actions

kv-toggle_namespace_tree = Toggle namespace tree

kv-toggle_favourites_only_filter = Toggle favourites-only filter

kv-new_key = New key

kv-importing = Importing…

kv-commands_ready = { $count } command(s) ready to run

kv-import_destructive = { $count } destructive command(s) in this file:

kv-import_keys = Import keys

kv-this_cant_be_undone = This can't be undone.

kv-delete_key = Delete key

kv-rename_key = Rename key

kv-toggle_favourite = Toggle favourite

kv-close = Close

kv-close_inspector = Close inspector

kv-preview_truncated = Preview truncated

kv-edit = Edit

kv-edit_item = Edit item

kv-delete = Delete

kv-delete_item = Delete item

kv-no_consumers = No consumers.

kv-nothing_pending_all_delivered_entries_are_acknowledged = Nothing pending — all delivered entries are acknowledged.

kv-edit_element = Edit element

kv-delete_element = Delete element

kv-copied_one_key = Copied 1 key

kv-copied_keys_ok = Copied { $copied } keys

kv-copied_keys = Copied { $copied } key(s), { $failed } failed

kv-note = note…

kv-tags_comma_separated = tags, comma-separated…

kv-type_a_command_e_g_get_mykey_then_enter = Type a command, e.g. GET mykey, then Enter…

kv-console_hint = One command per line. # comments and blanks are skipped. ⌘↵ runs all.

kv-redis_batch_composer = Redis batch composer

kv-batch_stopped = Batch stopped — { $ok } ok, { $failed } failed

kv-batch_ran = Batch ran { $ok } command(s)

kv-batch_partial = Batch: { $ok } ok, { $failed } failed

kv-batch_destructive_confirm = This batch contains { $destructive } destructive command(s). Run all { $total } line(s)?

kv-tab_to_complete = Tab to complete

kv-keyspace_watching = watching { $pattern } — { $events } event(s), { $cfg }

kv-keyspace_idle = not watching — { $cfg }

kv-slowlog_loading = Loading slow log…

kv-slowlog_count = { $n } slow command(s)

kv-no_slow_commands_logged = No slow commands logged.

kv-monitor_paused = paused — { $n } line(s) held

kv-monitor_streaming = streaming every command — { $n } line(s)

kv-monitor_stopped = stopped (MONITOR streams every command the server runs)

kv-clients_loading = Loading clients…

kv-clients_count = { $n } connected client(s)

kv-no_connected_clients = No connected clients.

kv-channel_pattern_e_g_news = Channel pattern, e.g. news.*

kv-pubsub_listening = listening on "{ $pattern }", { $messages } message(s)

kv-pubsub_idle = not subscribed
