# The `notify` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

notify-statements_run = [{ $statements } státéméñt(s) rúñ, { $affected } röw(s) áfféçtéd]

notify-rows_affected = [{ $affected } röw(s) áfféçtéd]

notify-downloading_update = [Döwñlöádíñg úpdáté…]

notify-reset_problems = [Rését fíñíshéd wíth { $n } pröblém(s); sömé dátá máy rémáíñ]

notify-exported_rows = [Éxpörtéd { $rows } röw(s) tö { $path }]

notify-importing_rows = [Ímpörtíñg… { $rows } röw(s)]

notify-imported_rows = [Ímpörtéd { $rows } röw(s)]

notify-import_failed = [Ímpört fáíléd áftér { $rows } röw(s): { $message }]

notify-import_failed_bare = [Ímpört fáíléd: { $message }]

notify-import_cancelled = [Ímpört çáñçélléd ({ $rows } röw(s) képt)]

notify-import_cancelled_bare = [Ímpört çáñçélléd]
