# The `notify` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

notify-statements_run = { $statements } statement(s) run, { $affected } row(s) affected

notify-rows_affected = { $affected } row(s) affected

notify-downloading_update = Downloading update…

notify-reset_problems = Reset finished with { $n } problem(s); some data may remain

notify-exported_rows = Exported { $rows } row(s) to { $path }

notify-importing_rows = Importing… { $rows } row(s)

notify-imported_rows = Imported { $rows } row(s)

notify-import_failed = Import failed after { $rows } row(s): { $message }

notify-import_failed_bare = Import failed: { $message }

notify-import_cancelled = Import cancelled ({ $rows } row(s) kept)

notify-import_cancelled_bare = Import cancelled
