# The `transfer` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

transfer-finished_with_failures = [Tráñsfér fíñíshéd: { $rows } röw(s), { $failures } ítém(s) fáíléd]

transfer-finished = [Tráñsférréd { $rows } röw(s)]

transfer-failed = [Tráñsfér fáíléd: { $message }]

transfer-cancelled = [Tráñsfér çáñçélléd ({ $rows } röw(s) képt)]

transfer-running = [Tráñsférríñg…]

transfer-running_rows = [Tráñsférríñg… { $rows } röw(s)]

transfer-title = [Tráñsfér]
