# The `transfer` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

transfer-finished_with_failures = Transfer finished: { $rows } row(s), { $failures } item(s) failed

transfer-finished = Transferred { $rows } row(s)

transfer-failed = Transfer failed: { $message }

transfer-cancelled = Transfer cancelled ({ $rows } row(s) kept)

transfer-running = Transferring…

transfer-running_rows = Transferring… { $rows } row(s)

transfer-title = Transfer
