# The `assistant` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

assistant-default = [Défáúlt]

assistant-fast = [Fást]

assistant-writes = [wrítés]

assistant-save_key = [Sávé kéy]

assistant-add_an_anthropic_api_key_to_use_the_agent = [Ádd áñ Áñthröpíç ÁPÍ kéy tö úsé thé ágéñt.]

assistant-new_chat = [Ñéw çhát]

assistant-plan = [Pláñ]

assistant-subagent = [Súbágéñt]

assistant-working_badge = [wörkíñg]

assistant-working = [Wörkíñg…]

assistant-open = [Öpéñ]

assistant-html_report = [HTML répört]

assistant-agent_prompt = [Ágéñt prömpt]

assistant-message_claude_agent_for_commands = [Mésságé Çláúdé Ágéñt (/ för çömmáñds)]

assistant-search_conversations = [Séárçh çöñvérsátíöñs…]
