# The `assistant` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

assistant-default = Default

assistant-writes = writes

assistant-save_key = Save key

assistant-add_an_anthropic_api_key_to_use_the_agent = Add an Anthropic API key to use the agent.

assistant-new_chat = New chat

assistant-plan = Plan

assistant-subagent = Subagent

assistant-working_badge = working

assistant-working = Working…

assistant-open = Open

assistant-html_report = HTML report

assistant-agent_prompt = Agent prompt

assistant-message_claude_agent_for_commands = Message Claude Agent (/ for commands)

assistant-search_conversations = Search conversations…
