# The `filter` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

filter-filter_expression = [Fíltér éxpréssíöñ]

filter-forget_this_filter = [Förgét thís fíltér]

filter-add_this_term_to_the_filter_and = [Ádd thís térm tö thé fíltér (ÁÑD)]

filter-add_filter_term = [Ádd fíltér térm]

filter-recent_filters_for_this_table_in_the_box = [Réçéñt fíltérs för thís táblé (↑/↓ íñ thé böx)]

filter-recent_filters = [Réçéñt fíltérs]

filter-filter = [Fíltér]

filter-remove_this_term = [Rémövé thís térm]

filter-re_apply_the_last_filter_that_returned_rows = [Ré-ápply thé lást fíltér thát rétúrñéd röws]

filter-find = [Fíñd]
