# The `filter` catalog. Generated by scripts/i18n-extract.py; do not
# edit by hand. The locale is this file's name, the folder is the UI area.
# Every locale mirrors these messages in its own file next to this one, so
# two translators never edit the same lines.
#
# Plural forms belong in the translation, not in the code:
#
#   some-message = { $n ->
#       [one] { $n } row
#      *[other] { $n } rows
#   }

filter-filter_expression = Filter expression

filter-forget_this_filter = Forget this filter

filter-add_this_term_to_the_filter_and = Add this term to the filter (AND)

filter-add_filter_term = Add filter term

filter-recent_filters_for_this_table_in_the_box = Recent filters for this table (↑/↓ in the box)

filter-recent_filters = Recent filters

filter-filter = Filter

filter-remove_this_term = Remove this term

filter-re_apply_the_last_filter_that_returned_rows = Re-apply the last filter that returned rows

filter-find = Find
